//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Reservation_No { get; set; }
        public string Customer_Name { get; set; }
        public int Driver_ID { get; set; }
        public System.DateTime Reservation_Date { get; set; }
        public string Vehicle_Number { get; set; }
    }
}
